apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::050491004063:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-CYR91WCHML4H
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::050491004063:role/UdacityFlaskDeployCBKubectlRole
      username: build      
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-27T19:09:55Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1520"
  uid: 18dbf6cd-6499-4271-947d-4f43b95073c5
